---
# Title The Generator
title:     That Really Blanks my Blank Generator

# Use this for an analogy, used for update page. EX: What is TRBMB?
shortname: TRBMB

# Who made the generator?
creator:   Chewsterchew

# Repo URL: THIS MUST BE Name/Repo. Ex: Chewsterchew/TRBMB-Gen
repourl:   Chewsterchew/TRBMB-Gen

# Footer Extra Content
## You'll probably want to delete this (unless you have a twitter and bot for it too?)
footer-extra: >
  <a href="http://ctt.ec/2Bofm">Tweet Us!</a>
  <a href="http://twitter.com/TRBMBPhraseGen">Twitter Bot</a><br/>
